baseURL = 'https://your-site.netlify.app'  # Update this to your actual URL
languageCode = 'en-us'
title = 'SimplyFrugalLife'
theme = 'PaperMod'

[params]
  # PaperMod specific settings
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
