[build]
  command = """
    mkdir -p themes &&
    git clone https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod &&
    hugo --gc --minify
  """
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.119.0"
